### ISSUE TITLE
Duplicate Broadcast with Anycable & Turbo Enabled Together

### ISSUE THREAD

**Issue by RailsCod3rFuture** [anycable/anycable-rails#148]
Expected Results:
**One message should show per POST action**
Actual Results:
**Two messages are showing per POST action, up until page refresh**

Gemspec: **ruby 2.7.1, rails 6.0, anycable-rails 1.0.4, redis 4.0, webpacker 4.0, hotwire-rails 0.1.2**

**Server Log:**
```
Started POST "/conversations/wDh4J0WMCs6C/conversation_comments" for 127.0.0.1 at 2021-01-01 10:23:07 -0500
Processing by ConversationCommentsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"O96fMmOdAbykBeJxkTx2iDBZogZ5UHz/VfsDLXbT56NB/iDTVlM4UwtY8tRTULOTaKgwV9aHizrv0DxyPS/fTg==", "conversation_comment"=>{"content"=>"action cable!", "user_id"=>"2"}, "conversation_id"=>"wDh4J0WMCs6C"}
  Conversation Load (0.3ms)  SELECT "conversations".* FROM "conversations" WHERE "conversations"."hash_id" = $1 ORDER BY "conversations"."id" ASC LIMIT $2  [["hash_id", "wDh4J0WMCs6C"], ["LIMIT", 1]]
  ↳ app/controllers/conversation_comments_controller.rb:18:in `set_conversation'
   (0.1ms)  BEGIN
  ↳ app/controllers/conversation_comments_controller.rb:9:in `create'
  ConversationComment Create (0.4ms)  INSERT INTO "conversation_comments" ("conversation_id", "user_id", "created_at", "updated_at", "content") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["conversation_id", 1], ["user_id", 2], ["created_at", "2021-01-01 15:23:07.446905"], ["updated_at", "2021-01-01 15:23:07.446905"], ["content", "action cable!"]]
  ↳ app/controllers/conversation_comments_controller.rb:9:in `create'
   (0.4ms)  COMMIT
  ↳ app/controllers/conversation_comments_controller.rb:9:in `create'
[ActiveJob] Enqueued Turbo::Streams::ActionBroadcastJob (Job ID: c157a165-f684-45fc-bfe9-1d48a5e3) to Async(default) with arguments: "Z2lkOi8vcmVzdW1lLWZ1dHVyZS1uZXh0L0NvbnZlcnNhdGlvbi8x", {:action=>:append, :target=>"conversation_comments", :locals=>{:conversation_comment=>#<GlobalID:0x00007f97614d91f8 @uri=#<URI::GID gid://rf-next/ConversationComment/102>>}, :partial=>"conversation_comments/conversation_comment"}
  Rendering conversation_comments/create.turbo_stream.erb
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/conversation_comments/_conversation_comment.html.erb:2
  Rendered conversation_comments/_conversation_comment.html.erb (Duration: 2.7ms | Allocations: 972)
  Rendered conversation_comments/create.turbo_stream.erb (Duration: 3.3ms | Allocations: 1068)
Completed 200 OK in 13ms (Views: 4.1ms | ActiveRecord: 1.7ms | Allocations: 5919)


  ConversationComment Load (0.3ms)  SELECT "conversation_comments".* FROM "conversation_comments" WHERE "conversation_comments"."id" = $1 LIMIT $2  [["id", 102], ["LIMIT", 1]]
[ActiveJob] [Turbo::Streams::ActionBroadcastJob] [c157a165-f684-45fc-bfe9-1d48a5e3] Performing Turbo::Streams::ActionBroadcastJob (Job ID: c157a165-f684-45fc-bfe9-1d48a5e3) from Async(default) enqueued at 2021-01-01T15:23:07Z with arguments: "Z2lkOi8vcmVzdW1lLWZ1dHVyZS1uZXh0L0NvbnZlcnNhdGlvbi8x", {:action=>:append, :target=>"conversation_comments", :locals=>{:conversation_comment=>#<GlobalID:0x00007f9760453720 @uri=#<URI::GID gid://resume-future-next/ConversationComment/102>>}, :partial=>"conversation_comments/conversation_comment"}
[ActiveJob] [Turbo::Streams::ActionBroadcastJob] [c157a165-f684-45fc-bfe9-1d48a5e3]   User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[ActiveJob] [Turbo::Streams::ActionBroadcastJob] [c157a165-f684-45fc-bfe9-1d48a5e3]   ↳ app/views/conversation_comments/_conversation_comment.html.erb:2
[ActiveJob] [Turbo::Streams::ActionBroadcastJob] [c157a165-f684-45fc-bfe9-1d48a5e3]   Rendered conversation_comments/_conversation_comment.html.erb (Duration: 2.0ms | Allocations: 907)
[ActiveJob] [Turbo::Streams::ActionBroadcastJob] [c157a165-f684-45fc-bfe9-1d48a5e3] [ActionCable] Broadcasting to Z2lkOi8vcmVzdW1lLWZ1dHVyZS1uZXh0L0NvbnZlcnNhdGlvbi8x: "<turbo-stream action=\"append\" target=\"conversation_comments\"><template><div class=\"p-1\">\n  <div class=\"user-message-bubble\" id=\"conversation_comment_102\">\n    <small><strong>DW</strong> <span><i class=\"fas fa-pencil-alt text-success\"></i></span> <span class=\"text-pink\">less than a minute</span> ago</small>\n    <br>\n    action cable!\n</div></div>\n</template></turbo-stream>"
[ActiveJob] [Turbo::Streams::ActionBroadcastJob] [c157a165-f684-45fc-bfe9-1d48a5e3] Performed Turbo::Streams::ActionBroadcastJob (Job ID: c157a165-f684-45fc-bfe9-1d48a5e3) from Async(default) in 3.0ms

```

Terminal 1
```
(base) DW-MBP:rf_next dw$ anycable-go --host=localhost --port=3334
  INFO 2021-01-01T15:02:22.443Z context=main Starting AnyCable 1.0.0 (pid: 3363, open file limit: 10240)
  INFO 2021-01-01T15:02:22.444Z context=main Handle WebSocket connections at http://localhost:3334/cable
  INFO 2021-01-01T15:02:22.444Z context=main Handle health connections at http://localhost:3334/health
  INFO 2021-01-01T15:02:22.444Z context=rpc RPC controller initialized: localhost:50051 (concurrency: 28, proto_versions: v0,v1)
  INFO 2021-01-01T15:02:22.447Z context=pubsub Subscribed to Redis channel: __anycable__
```

**Terminal 2**
```

(base) Darion-Wood-MBP:rf_next dwood$ RAILS_ENV=development bundle exec anycable
Starting AnyCable gRPC server (pid: 2815, workers_num: 30)
AnyCable version: 1.0.1 (proto_version: v1)
gRPC version: 1.34.0
Serving Rails application from ./config/environment.rb
Broadcasting Redis channel: __anycable__
RPC server is starting...
RPC server is listening on 127.0.0.1:50051
[AnyCable sid=3wuZyV3MPWY3APWwx39dw] RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {}, istate: {}>>
/Users/dwood/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/anycable-rails-1.0.4/lib/anycable/rails/actioncable/connection.rb:30: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/dwood/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/anycable-rails-1.0.4/lib/anycable/rails/actioncable/connection.rb:34: warning: The called method `initialize' is defined here
[AnyCable sid=3wuZyV3MPWY3APWwx39dw] Started "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:02:33 -0500
[AnyCable sid=3wuZyV3MPWY3APWwx39dw] RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=3wuZyV3MPWY3APWwx39dw] Turbo::StreamsChannel is transmitting the subscription confirmation
[AnyCable sid=3wuZyV3MPWY3APWwx39dw] RPC Disconnect: <AnyCable::DisconnectRequest: identifiers: "{}", subscriptions: ["{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}"], env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"cookie"=>"", "REMOTE_ADDR"=>"127.0.0.1"}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=3wuZyV3MPWY3APWwx39dw] Finished "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:05:59 -0500 (Closed)
[AnyCable sid=tZXTXkg6FNZSq-7G5zkrW] RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {}, istate: {}>>
[AnyCable sid=tZXTXkg6FNZSq-7G5zkrW] Started "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:05:59 -0500
[AnyCable sid=tZXTXkg6FNZSq-7G5zkrW] RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=tZXTXkg6FNZSq-7G5zkrW] Turbo::StreamsChannel is transmitting the subscription confirmation
[AnyCable sid=tZXTXkg6FNZSq-7G5zkrW] RPC Disconnect: <AnyCable::DisconnectRequest: identifiers: "{}", subscriptions: ["{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}"], env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=tZXTXkg6FNZSq-7G5zkrW] Finished "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:08:10 -0500 (Closed)
[AnyCable sid=PL17AXSX9ZnvVYMHHMy0l] RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {}, istate: {}>>
[AnyCable sid=PL17AXSX9ZnvVYMHHMy0l] Started "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:08:29 -0500
[AnyCable sid=PL17AXSX9ZnvVYMHHMy0l] RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=PL17AXSX9ZnvVYMHHMy0l] Turbo::StreamsChannel is transmitting the subscription confirmation
[AnyCable sid=PL17AXSX9ZnvVYMHHMy0l] RPC Disconnect: <AnyCable::DisconnectRequest: identifiers: "{}", subscriptions: ["{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}"], env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=PL17AXSX9ZnvVYMHHMy0l] Finished "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:11:43 -0500 (Closed)
[AnyCable sid=2KYm5nIrAjyr-Oaa58MgO] RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {}, istate: {}>>
[AnyCable sid=2KYm5nIrAjyr-Oaa58MgO] Started "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:11:44 -0500
[AnyCable sid=2KYm5nIrAjyr-Oaa58MgO] RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=2KYm5nIrAjyr-Oaa58MgO] Turbo::StreamsChannel is transmitting the subscription confirmation
[AnyCable sid=2KYm5nIrAjyr-Oaa58MgO] RPC Disconnect: <AnyCable::DisconnectRequest: identifiers: "{}", subscriptions: ["{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}"], env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=2KYm5nIrAjyr-Oaa58MgO] Finished "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:19:16 -0500 (Closed)
[AnyCable sid=5Boi-AXh_YYjY3KHbOr8H] RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"cookie"=>"", "REMOTE_ADDR"=>"127.0.0.1"}, cstate: {}, istate: {}>>
[AnyCable sid=5Boi-AXh_YYjY3KHbOr8H] Started "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:19:17 -0500
[AnyCable sid=5Boi-AXh_YYjY3KHbOr8H] RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=5Boi-AXh_YYjY3KHbOr8H] Turbo::StreamsChannel is transmitting the subscription confirmation
[AnyCable sid=5Boi-AXh_YYjY3KHbOr8H] RPC Disconnect: <AnyCable::DisconnectRequest: identifiers: "{}", subscriptions: ["{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}"], env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=5Boi-AXh_YYjY3KHbOr8H] Finished "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:22:57 -0500 (Closed)
[AnyCable sid=MZeYnOCH7kJDg1QsAzFU3] RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {}, istate: {}>>
[AnyCable sid=MZeYnOCH7kJDg1QsAzFU3] Started "/cable" [AnyCable] for 127.0.0.1 at 2021-01-01 10:22:57 -0500
[AnyCable sid=MZeYnOCH7kJDg1QsAzFU3] RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"IloybGtPaTh2Y21WemRXMWxMV1oxZEhWeVpTMXVaWGgwTDBOdmJuWmxjbk5oZEdsdmJpOHgi--65df3f25d2df99bd867b8e6adf7432a7ee91a12dfa0ba52c8ae42f702b8f0904\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:3334/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>""}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
[AnyCable sid=MZeYnOCH7kJDg1QsAzFU3] Turbo::StreamsChannel is transmitting the subscription confirmation

```

```
(base) Darion-Wood-MBP:rf_next dwood$ anycable-go --host=localhost --port=3334
  INFO 2021-01-01T15:02:22.443Z context=main Starting AnyCable 1.0.0 (pid: 3363, open file limit: 10240)
  INFO 2021-01-01T15:02:22.444Z context=main Handle WebSocket connections at http://localhost:3334/cable
  INFO 2021-01-01T15:02:22.444Z context=main Handle health connections at http://localhost:3334/health
  INFO 2021-01-01T15:02:22.444Z context=rpc RPC controller initialized: localhost:50051 (concurrency: 28, proto_versions: v0,v1)
  INFO 2021-01-01T15:02:22.447Z context=pubsub Subscribed to Redis channel: __anycable__
```

**application.html.erb**

```
<head>
<%= action_cable_meta_tag %>
</head>
```

**Network/WS shows the below**
```
cable status 101
conversation_comments status blank
```

**Comment by RailsCod3rFuture** [comment]
Hold on, I see actioncable in my package.json. I will see if removing that, does the trick.

**Comment by RailsCod3rFuture** [comment]
fixed it. turbo_stream.append does not need to be included in create.turbo_stream.erb
