### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/cable")

### ISSUE THREAD

**Issue by samgooi4189** [anycable/anycable-rails#41]
Hi, I wanted to use anycable for a fresh project and I encounter problem with routes.

When rails is running with anycable and anycable-go,
I got the following error
```
Started GET "/cable" for 127.0.0.1 at 2018-04-12 23:10:29 +0800
Started GET "/cable" for 127.0.0.1 at 2018-04-12 23:10:29 +0800
  
  
ActionController::RoutingError (No route matches [GET] "/cable"):
ActionController::RoutingError (No route matches [GET] "/cable"):
  
  
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.3) lib/puma/configuration.rb:225:in `call'
puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
puma (3.11.3) lib/puma/server.rb:438:in `process_client'
puma (3.11.3) lib/puma/server.rb:302:in `block in run'
puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.3) lib/puma/configuration.rb:225:in `call'
puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
puma (3.11.3) lib/puma/server.rb:438:in `process_client'
puma (3.11.3) lib/puma/server.rb:302:in `block in run'
puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Here are the config/application.rb
```
    config.action_cable.url = ENV['CABLE_URL']
    config.action_cable.mount_path = ENV['CABLE_URL'] ? nil : "/cable"
```

What should I do to fix this?
I am using rails 5.2, ruby 2.4.3, anycable-go 0.5.4

**Comment by palkan** [comment]
Hi @samgooi4189,

What is your `CABLE_URL` env value? Looks like it's not set, and Action Cable tries to use the default url (`/cable`).

Or, maybe, you have hard-coded `/cable` in your client

**Comment by samgooi4189** [comment]
The issue does not happen again after disabling spring

**Comment by samgooi4189** [comment]
starting rails with:
CABLE_URL='ws://localhost:3334/cable' bundle exec rails s -b 0.0.0.0

starting anycable with:
bin/anycable

starting anycable-go with:
./bin/anycable-go -rpc=localhost:50051 -headers=cookie,x-api-token -redis=redis://localhost:6379/2 -redis_channel="__anycable__" -addr=localhost:3334 -log
