### ISSUE TITLE
Error while establishing connection

### ISSUE THREAD

**Issue by McAlexVrn** [anycable/anycable-rails#5]
Hello!
I've used this gem some time ago, and I really love it! But now, after fresh install of this gem and `anycable-go` server, I'm getting strange error when I want to connect to server:

```
[2017-06-26T09:59:19.578424 #15951] FATAL -- : [e9631f7b-6a54-4eee-85aa-013b68c9e31d] **ArgumentError (wrong number of arguments (given 2, expected 1)):**
F, [2017-06-26T09:59:19.578604 #15951] FATAL -- : [e9631f7b-6a54-4eee-85aa-013b68c9e31d]   
F, [2017-06-26T09:59:19.578794 #15951] FATAL -- : [e9631f7b-6a54-4eee-85aa-013b68c9e31d] anycable-rails (0.4.4) lib/anycable/rails/actioncable/connection.rb:28:in `initialize'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actioncable (5.0.4) lib/action_cable/server/base.rb:28:in `new'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actioncable (5.0.4) lib/action_cable/server/base.rb:28:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:26:in `each'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/journey/router.rb:26:in `serve'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/routing/route_set.rb:725:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack (2.0.3) lib/rack/etag.rb:25:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack (2.0.3) lib/rack/head.rb:12:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] activesupport (5.0.4) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] activesupport (5.0.4) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] activesupport (5.0.4) lib/active_support/callbacks.rb:90:in `run_callbacks'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] railties (5.0.4) lib/rails/rack/logger.rb:36:in `call_app'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] railties (5.0.4) lib/rails/rack/logger.rb:24:in `block in call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] activesupport (5.0.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] activesupport (5.0.4) lib/active_support/tagged_logging.rb:26:in `tagged'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] activesupport (5.0.4) lib/active_support/tagged_logging.rb:69:in `tagged'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] railties (5.0.4) lib/rails/rack/logger.rb:24:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] activesupport (5.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] actionpack (5.0.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] railties (5.0.4) lib/rails/engine.rb:522:in `call'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] unicorn (5.3.0) lib/unicorn/http_server.rb:606:in `process_client'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] unicorn (5.3.0) lib/unicorn/http_server.rb:702:in `worker_loop'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] unicorn (5.3.0) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] unicorn (5.3.0) lib/unicorn/http_server.rb:142:in `start'
[e9631f7b-6a54-4eee-85aa-013b68c9e31d] unicorn (5.3.0) bin/unicorn:126:in `<top (required)>'
```

Any suggestions? What additional information I need to provide?

**Comment by palkan** [comment]
Looks like you're connecting through built-in ActionCable server and not through `anycable-go`.

Have you specified `config.action_cable.url` in your configuration to point to `anycable-go` endpoint?

And it makes sense to disable the default server too:

```ruby
config.action_cable.mount_path = nil
```

**Comment by McAlexVrn** [comment]
Yep, I really tried to connect to wrong server. Thank you in advice!
