### ISSUE TITLE
Issues with ruby 2.6.0

### ISSUE THREAD

**Issue by coinfalcon-github** [anycable/anycable-rails#71]
**Ruby version:**
2.6.0

**Rails version:**
5.2.2

**`anycable` gem version:**
0.6.1

**`anycable-rails` gem version:**
0.6.2

**`grpc` gem version:**
1.18.0

### What did you do?
created a new rails app with 2.6.0 and added `gem 'anycable-rails'` to my Gemfile

### What did you expect to happen?
`bundle exec anycable` should boot anycable

### What actually happened?
```
➜  testapp git:(master) ✗ bundle exec anycable
bundler: failed to load command: anycable (/Users/nomis/.rbenv/versions/2.6.0/bin/anycable)
LoadError: cannot load such file -- google/protobuf_c
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:50:in `require'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:50:in `rescue in <top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:47:in `<top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/grpc-1.18.0-universal-darwin/src/ruby/pb/grpc/health/v1/health_pb.rb:4:in `require'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/grpc-1.18.0-universal-darwin/src/ruby/pb/grpc/health/v1/health_pb.rb:4:in `<top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/grpc-1.18.0-universal-darwin/src/ruby/pb/grpc/health/v1/health_services_pb.rb:23:in `require'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/grpc-1.18.0-universal-darwin/src/ruby/pb/grpc/health/v1/health_services_pb.rb:23:in `<top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/grpc-1.18.0-universal-darwin/src/ruby/pb/grpc/health/checker.rb:16:in `require'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/grpc-1.18.0-universal-darwin/src/ruby/pb/grpc/health/checker.rb:16:in `<top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/anycable-0.6.1/lib/anycable/server.rb:4:in `require'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/anycable-0.6.1/lib/anycable/server.rb:4:in `<top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/anycable-0.6.1/lib/anycable.rb:11:in `require'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/anycable-0.6.1/lib/anycable.rb:11:in `<top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/anycable-0.6.1/lib/anycable/cli.rb:5:in `require'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/anycable-0.6.1/lib/anycable/cli.rb:5:in `<top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/anycable-0.6.1/bin/anycable:3:in `require_relative'
  /Users/nomis/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/anycable-0.6.1/bin/anycable:3:in `<top (required)>'
  /Users/nomis/.rbenv/versions/2.6.0/bin/anycable:23:in `load'
  /Users/nomis/.rbenv/versions/2.6.0/bin/anycable:23:in `<top (required)>'
```

**Comment by Envek** [comment]
Try to use gem `google-protobuf` from git. Place following to your Gemfile:
```rb
gem "google-protobuf", git: "https://github.com/google/protobuf" 
```

**Comment by Envek** [comment]
See:
 1. https://github.com/protocolbuffers/protobuf/issues/5161
 2. https://github.com/protocolbuffers/protobuf/pull/5537

So waiting when new release of `google-protobuf` will be released.

**Comment by coinfalcon-github** [comment]
Works, should we keep this open till a new gem of protobuf is released?

**Comment by palkan** [comment]
>  should we keep this open till a new gem of protobuf is released?

Yep, makes sense. I'll add a link to this issue to the Readme.

Thanks!

**Comment by Vasfed** [comment]
protobuf 3.7.0.rc.2 can now be used instead of pulling from git:

```ruby
gem "google-protobuf", '>=3.7.0.rc.2'
```

**Comment by palkan** [comment]
@Vasfed Thanks! Updated readme.
