### ISSUE TITLE
Errors in log files

### ISSUE THREAD

**Issue by kernow** [anycable/anycable-rails#79]
### Tell us about your environment

**Ruby version:**
2.5.1

**Rails version:**
5.2.2

**`anycable` gem version:**
0.6.1

**`anycable-rails` gem version:**
0.6.2

**`grpc` gem version:**
1.18.0

### What happened?

We've been running anycable in production for a few days now. We went to deploy our rails app and found the partition with our rails log file had run out of disk space. On investigation our rails look had ballooned to 26GB cause by this log entry:

```
I, [2019-02-09T02:36:47.888116 #17304]  INFO -- : [AnyCable sid=RtYAn2no_65qw9Pj83lp8F] [ActionCable] [8777] SessionChannel is transmitting the subscription confirmati
on
E, [2019-02-09T02:36:48.280051 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
E, [2019-02-09T02:36:48.280128 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
E, [2019-02-09T02:36:48.280159 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
E, [2019-02-09T02:36:48.280186 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
E, [2019-02-09T02:36:48.280212 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
E, [2019-02-09T02:36:48.280236 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
E, [2019-02-09T02:36:48.280302 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
E, [2019-02-09T02:36:48.280327 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
E, [2019-02-09T02:36:48.280350 #17304] ERROR -- : Errno::EMFILE: Too many open files - accept(2)
        /usr/lib/ruby/2.5.0/socket.rb:1313:in `__accept_nonblock'
...
```
The `Errno::EMFILE: Too many open files` is repeated millions of times.

We have anycable-go running on 1 server, then an AWS network load balancer facilitating gRPC traffic to two application servers running the anycable gems. Both application servers saw the errors at a similar time, however 1 server only created a 3GB log file where as the other generated a 26GB log file and saw many times more of these errors.

I'm assuming this is to do with the anycable gem(s) so I'm posting here to get some help with diagnosing what the problem is. Thanks

**Comment by palkan** [comment]
Do you have anything else running on the application servers?

That problem could happen on the WS server (and requires some [tuning](https://docs.anycable.io/#/go_os_tuning) to handle tons of connection).

Could you share you system limits settings? For example, on Ubuntu we're looking for `/etc/sysctl.conf` (`fs.file-max`) and `/etc/security/limits.conf `.

Could there be a manual `ulimit` set for the command?

And one more thing we could try is to take a look at `lsof | wc -l` and the list itself (`lsof`) while server is running and raising the exceptions.

Also, I noticed that you're using the latest `grpc` gem; could you check the previous version (1.17.x)?

**Comment by kernow** [comment]
Hi @palkan,

anycable-go is not on the application servers which had the issue.

The application servers run:

* nginx
* A rails app
* anycable-rails
* Delayed job worker
* ufw firewall
* AWS cloudwatch agents for sending log files to cloudwatch

`/etc/sysctl.conf` doesn't have any uncommented lines in it so I assume it's running defaults.
`/etc/security/limits.conf` also doesn't have any uncommented lines to I assume defaults again.

We run ubuntu 16.04 LTS

We are not setting a `ulimit` anywhere for anything running on the servers. We run anycable-rails using systemd

```
[Unit]
Description=AnyCableRails Server
ConditionPathExists=/home/deploy/app/current/bin/anycable
After=network.target

[Service]
Type=simple
PIDFile=/var/run/anycable-rails.pid
User=deploy
Group=users
WorkingDirectory=/home/deploy/app/current

Restart=always
RestartSec=10

ExecStart=/home/deploy/app/current/bin/anycable --require=/home/deploy/app/current/config/environment.rb

Environment=RAILS_ENV=production
Environment=ANYCABLE_HTTP_HEALTH_PORT=54321
EnvironmentFile=/home/deploy/.env_vars_systemd

[Install]
WantedBy=multi-user.target
```

The server has not experienced this error again so far, `lsof` has a count of 13605 but probably not of much use as the error was not occurring when the command was run.

I've not tried running 1.17.x of gRPC, is it worth switching at this stage as we have only experienced the issue the 1 time?

Thanks

**Comment by palkan** [comment]
> We are not setting a `ulimit` anywhere for anything running on the servers

Can you show the output of `ulimit -a`?

**Comment by palkan** [comment]
@kernow 
And also could you check the limits for the anycable process by:

```sh
$ cat /proc/<ANYCABLE PID>/limits
```

**Comment by kernow** [comment]
@palkan here are the outputs from the commands

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30689
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 30689
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

```
$ cat /proc/5168/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             30689                30689                processes 
Max open files            1024                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       30689                30689                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us 
```

**Comment by palkan** [comment]
Do you run everything on this server on behalf of the same user?
Then 1024 could be exceeded in total (given that you a bunch of things running on this machine).

It makes sense to increase this limit (it might worth checking the system wide limit as well: `cat /proc/sys/fs/file-max`).

1024 should be pretty enough for RPC server itself.

**Comment by kernow** [comment]
@palkan the rails app (using passenger), anycable-rails and the Delayed job worker all run under the same user, nginx and everything else run as other users.

```
$ cat /proc/sys/fs/file-max
783512
```

Do you think I should raise the max open files limit for the user as there are 3 things running under this user?

**Comment by palkan** [comment]
> Do you think I should raise the max open files limit for the user as there are 3 things running under this user?

Yeah, 1024 is too low limit for production apps.

Btw, what is your `worker_connections` and `worker_processes` for nginx? Have you seen `too many open files` in nginx `error.log`? So, `worker_connections * worker_processes` is a number of descriptors that could be open for connection under the load.

The worst case scenario is that you have a file descriptors leak somewhere in your code (or in some of your deps, including application servers).

**Comment by kernow** [comment]
@palkan Nginx
```
worker_connections 1024
worker_processes 2
```
Although nginx runs as a different user to the rails app and anycable gem.

I haven't seen that error in the nginx logs but I've never looked for it, I'll take a look and see. We only have a couple of weeks of data as these servers have been newly built, we build new servers using ansible when changing any configuration rather than updating existing ones.

I will look at raising the file limit and see how we go. Thank you for the assistance and responsiveness, most helpful and appreciated.

**Comment by cdalbergue** [comment]
Hi @kernow,

Have you solved your issue yet ?

I had the same problem with anycable-go when the limit for open files was too low (was at 1024).

If you run your anycable-go server with a systemd service, you could use the built-in syntax: anycable-go.service file, under Service
```
[Service]
Type=simple
LimitNOFILE=infinity
```

**Comment by kernow** [comment]
@palkan @cdalbergue so after 10 months of issue free operation we have been hit by this issue again over xmas ☹️

I set the soft limit to 2048 and the hard limit to 4096 in Feb last year and have not had any issues until 28th December. What I find strange is that our usage over this holiday period is very low compared to normal operation. I would have expected this issue to surface when usage is higher rather than lower. This got me thinking what the difference is between normal operation and the xmas period which lead me to deployment and restarting the service...

During most of the year we deploy new code every day other than Friday and weekends. As part of our code deployment the anycable rails process will be restarted so the longest the anycable process will be running without being restarted would be 3-4 days in general (although there has been some periods when we haven't deployed for over a week). Over the xmas period we have not deployed any new code so anycable would not have been restarted. Our last deployment before the holiday period was 19th December, we then experienced the open file issue 11 days later on the 30th December. Restarting the anycable process resolved the issue.

I'm wondering if this could be related in any way to the length of time the process has been running?

Looking at the servers today so see how many open files there are:

Server 1: (anycable process has been running for 4 days)
Anycable Process: 427
Total for user: 1072

Server 2: (anycable process has been running for 15 days)
Anycable Process: 401
Total for user: 1051

We are still operating at around 2/3 of the normal traffic we would see outside of holiday times for the above numbers.

Unfortunately I don't have any data for the number of open file for when the problem occured as I was in "get it back running" mode, not all that helpful.

Obviously we would like to avoid this issue in future if possible. Would increasing the open file limit again be likely to solve this issue or could this be caused by a runaway process that would cause problems no matter that the limit it set to?

Thanks

**Comment by palkan** [comment]
> Looking at the servers today so see how many open files there are:

Looks like running for a few days and for a dozen is the same.

What's interesting here is that the total number for the user is about 2x more than the AnyCable owns. Do you know the source of the other ~500 open FDs?

Do you have any information about the number of _attempted connections_ on Dec 30th? Maybe, NGINX access logs or similar. Probably, there is an issues with TCP sockets being in the TIME_WAIT state. Though the chance is low.

> Would increasing the open file limit again be likely to solve this issue or could this be caused by a runaway process that would cause problems no matter that the limit it set to?

Increasing the limit will definitely help but won't provide 100% guarantee. The best solution is to monitor the number of open files and react on the high values somehow (i.e., restart a server).

**Comment by kernow** [comment]
> What's interesting here is that the total number for the user is about 2x more than the AnyCable owns. Do you know the source of the other ~500 open FDs?

We also run a rails app, sidekiq worker and skylight under the same user which would explain the additional open files.

> Do you have any information about the number of attempted connections on Dec 30th? Maybe, NGINX access logs or similar. Probably, there is an issues with TCP sockets being in the TIME_WAIT state. Though the chance is low.

I'll take a look back through the logs to see if I can see anything relevant.

If there is a network issue that prevents connections for a period of time would the number of open files be expected to increase substantially?

**Comment by cdalbergue** [comment]
Hi @kernow 

> If there is a network issue that prevents connections for a period of time would the number of open files be expected to increase substantially?

I don't think so.. I think the FDs are only use between the anycable and the websocket server. Having a network issue won't increase the use of these two components.

Other than that, I totally agree with @palkan... I think that the only thing I could do at the time was to schedule a server restart to be "consistent".
